---
- name: "geoip: Install nginx packages for geoip support"
  package:
    name: "{{ geoip_extra_pkg }}"
    state: "present"

- name: "geoip: Add script to update geoip databases"
  template:
    src: "nginx_geoip_update_databases.sh.j2"
    dest: "/usr/local/bin/nginx_geoip_update_databases.sh"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0700'

- name: "geoip: Create update geoip log file"
  file:
    path: "/var/log/geoip-update.log"
    state: touch
    owner: "{{ nginx_user }}"

- name: "geoip: Create geoip dir for databases"
  file:
    path: "/etc/nginx/geoip"
    state: directory
    owner: "{{ nginx_user }}"
    mode: '0755'

- name: "geoip: Run update geoip databases"
  become: "yes"
  become_user: "{{ nginx_user }}"
  command:
    cmd: "/usr/local/bin/nginx_geoip_update_databases.sh"

- name: "geoip: Add cronjob to daily update maxminddb database"
  cron:
    name: "nginx_geoip_update_databases"
    minute: "0"
    hour: "3"
    day: "*"
    month: "*"
    weekday: "*"
    user: "{{ nginx_user }}"
    job: "/usr/local/bin/nginx_geoip_update_databases.sh"
    cron_file: "nginx_geoip_update_databases"
